chore: agg index scan without group by column
datafuselabs/databend pull request #12545
Opened 2023-08-22 10:33 UTC by ariesdevil

I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Support agg index scan without group by column

- Closes #issue

2023-08-22 12:25 UTC, RinChanNOWWW requested changes
Better to add a new case to `test_fuzz` unit test.

2023-08-22 12:29 UTC, RinChanNOWWW commented on src/query/service/src/pipelines/processors/transforms/aggregator/transform_single_key.rs
> +                let state_place = self.temp_place;
This `state_place` should add offset.

2023-08-23 02:18 UTC, RinChanNOWWW approved these changes
LGTM

2023-08-23 07:07 UTC, sundy-li approved these changes

2023-08-23 08:00 UTC, merged