Feat dict 2
datafuselabs/databend pull request #16178
Opened 2024-08-03 10:46 UTC by Winnie-Hong0927

I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/

## Summary

## Tests

- [x] Unit Test
- [ ] Logic Test
- [ ] Benchmark Test
- [ ] No Test - _Explain why_

## Type of change

- [ ] Bug Fix (non-breaking change which fixes an issue)
- [x] New Feature (non-breaking change which adds functionality)
- [ ] Breaking Change (fix or feature that could cause existing functionality not to work as expected)
- [ ] Documentation Update
- [ ] Refactoring
- [ ] Performance Improvement
- [ ] Other (please describe):

2024-08-03 14:24 UTC, drmingdrmer requested changes
Add some doc comment explain the introduced data structure, such as the key/value layout in meta-service.

In general, try not to use an error code for not-found or already-exists. Using the map API style would be better: a `get` operation should return an `Option<T>`, `Some` for successful `get` and `None` for a not-found error. 

> Reviewed 1 of 25 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/16178#-:-O3Nb5Yl7dcR-S_KMoWf:brjv7wf)* status: 1 of 30 files reviewed, 1 unresolved discussion (waiting on @Winnie-Hong0927)

___
*[`src/meta/app/src/schema/dictionary.rs` line 96 at r2](https://reviewable.io/reviews/datafuselabs/databend/16178#-O3NZtMZ0Ui1Tq_Kuh7F:-O3NZtMZ0Ui1Tq_Kuh7G:b-1tts73) ([raw file](https://github.com/datafuselabs/databend/blob/506ee1e34f337cc886d3878695fe5f7d763dbe79/src/meta/app/src/schema/dictionary.rs#L96)):*
> ```XML
>     pub db_name: String,
>     pub dictionary_name: String,
> }
> ```

Using `database_id` instead of `db_name` if possible. `xxx_id` is the unique identifier. A database can be renamed.

And there is already `DBIdDictionaryNameIdent`, this struct can be replaced with it.



_Code quote:_
```XML
    pub db_name: String,
    pub dictionary_name: String,
}
```


<!-- Sent from Reviewable.io -->

2024-08-08 15:28 UTC, drmingdrmer requested changes
> Reviewed 3 of 25 files at r2, 1 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/16178)* status: 26 of 34 files reviewed, 11 unresolved discussions (waiting on @b41sh and @Winnie-Hong0927)

___
*[`src/meta/api/src/schema_api_impl.rs` line 4750 at r6](https://reviewable.io/reviews/datafuselabs/databend/16178#-O3m_G-77OLhSQc-EKMo:-O3m_G-77OLhSQc-EKMp:bxufn9n) ([raw file](https://github.com/datafuselabs/databend/blob/7349334a84ccb63d774b7cfec7939b742713ccb5/src/meta/api/src/schema_api_impl.rs#L4750)):*
> ```XML
>     condition: &mut Vec<TxnCondition>,
>     if_then: &mut Vec<TxnOp>,
> ) -> Result<(u64, u64), KVAppError> {
> ```

All `if_delete` to the call to `construct_drop_dictionary_txn_operations` is `true`, this argument can be removed.

And without mark-delete, to drop a dictionary you only need an `Upsert::delete()`. There is no need to use a transaction of get-then-update



_Code quote:_
```XML
async fn construct_drop_dictionary_txn_operations(
    kv_api: &(impl kvapi::KVApi<Error = MetaError> + ?Sized),
    dbid_dict_name: &DBIdDictionaryName,
    drop_if_exists: bool,
    if_delete: bool,
    condition: &mut Vec<TxnCondition>,
    if_then: &mut Vec<TxnOp>,
) -> Result<(u64, u64), KVAppError> {
```
___
*[`src/meta/api/src/schema_api_impl.rs` line 5486 at r6](https://reviewable.io/reviews/datafuselabs/databend/16178#-O3ma2NK3lKeCbnATyhr:-O3ma2NK3lKeCbnATyhs:b7pxm3y) ([raw file](https://github.com/datafuselabs/databend/blob/7349334a84ccb63d774b7cfec7939b742713ccb5/src/meta/api/src/schema_api_impl.rs#L5486)):*
> ```XML
>     name_key: &DBIdDictionaryName,
> ) -> Result<(u64, u64, u64, Option<DictionaryMeta>), KVAppError> {
>     let (dictionary_id_seq, dictionary_id) = get_u64_value(kv_api, name_key).await?;
> ```

`get_u64_value` returns `0,0` if not found. You should deal with this return value and return at once.
___
*[`src/meta/app/src/app_error.rs` line 1126 at r6](https://reviewable.io/reviews/datafuselabs/databend/16178#-O3maPgs1nVwODV7RBDO:-O3maPgt9eYQ0q7-Mxr1:b6ay7t2) ([raw file](https://github.com/datafuselabs/databend/blob/7349334a84ccb63d774b7cfec7939b742713ccb5/src/meta/app/src/app_error.rs#L1126)):*
> ```XML
> #[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, thiserror::Error)]
> #[error("GetDictionaryWithDropTime: get {dictionary_name} with drop time")]
> pub struct GetDictionaryWithDropTime {
> ```

This error can be removed if there is no mark-delete provided.



_Code quote:_
```XML
GetDictionaryWithDropTime 
```
___
*[`src/meta/proto-conv/tests/it/v105_dictionary_meta.rs` line 45 at r6](https://reviewable.io/reviews/datafuselabs/databend/16178#-O3macO59kQp7nbYAGPh:-O3macO59kQp7nbYAGPi:b-hw5hci) ([raw file](https://github.com/datafuselabs/databend/blob/7349334a84ccb63d774b7cfec7939b742713ccb5/src/meta/proto-conv/tests/it/v105_dictionary_meta.rs#L45)):*
> ```XML
>     //     108, 101, 66, 23, 50, 48, 50, 52, 45, 48, 56, 45, 48, 53, 32, 48, 55, 58, 48, 48, 58, 48,
>     //     48, 32, 85, 84, 67, 160, 6, 105, 168, 6, 24,
>     // ];
> ```

What's this comment for?



_Code quote:_
```XML
    // let bytes = vec![
    //     10, 7, 109, 121, 95, 100, 105, 99, 116, 18, 5, 77, 121, 83, 81, 76, 26, 17, 10, 8, 100, 97,
    //     116, 97, 98, 97, 115, 101, 18, 5, 109, 121, 95, 100, 98, 26, 17, 10, 4, 104, 111, 115, 116,
    //     18, 9, 108, 111, 99, 97, 108, 104, 111, 115, 116, 26, 16, 10, 8, 112, 97, 115, 115, 119,
    //     111, 114, 100, 18, 4, 49, 50, 51, 52, 26, 12, 10, 4, 112, 111, 114, 116, 18, 4, 51, 51, 48,
    //     54, 26, 16, 10, 8, 117, 115, 101, 114, 110, 97, 109, 101, 18, 4, 114, 111, 111, 116, 34,
    //     123, 10, 43, 10, 7, 117, 115, 101, 114, 95, 105, 100, 26, 26, 178, 2, 17, 154, 2, 8, 66, 0,
    //     160, 6, 105, 168, 6, 24, 160, 6, 105, 168, 6, 24, 160, 6, 105, 168, 6, 24, 160, 6, 105,
    //     168, 6, 24, 10, 30, 10, 9, 117, 115, 101, 114, 95, 110, 97, 109, 101, 26, 9, 146, 2, 0,
    //     160, 6, 105, 168, 6, 24, 32, 1, 160, 6, 105, 168, 6, 24, 10, 28, 10, 7, 97, 100, 100, 114,
    //     101, 115, 115, 26, 9, 146, 2, 0, 160, 6, 105, 168, 6, 24, 32, 2, 160, 6, 105, 168, 6, 24,
    //     18, 6, 10, 1, 97, 18, 1, 98, 24, 3, 160, 6, 105, 168, 6, 24, 42, 7, 117, 115, 101, 114, 32,
    //     105, 100, 42, 9, 117, 115, 101, 114, 32, 110, 97, 109, 101, 42, 7, 97, 100, 100, 114, 101,
    //     115, 115, 50, 1, 0, 58, 15, 99, 111, 109, 109, 101, 110, 116, 95, 101, 120, 97, 109, 112,
    //     108, 101, 66, 23, 50, 48, 50, 52, 45, 48, 56, 45, 48, 53, 32, 48, 55, 58, 48, 48, 58, 48,
    //     48, 32, 85, 84, 67, 160, 6, 105, 168, 6, 24,
    // ];
```


<!-- Sent from Reviewable.io -->

2024-08-09 02:54 UTC, drmingdrmer requested changes
> Reviewed 2 of 7 files at r6, 2 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/16178)* status: 30 of 34 files reviewed, 16 unresolved discussions (waiting on @b41sh and @Winnie-Hong0927)

___
*[`src/meta/app/src/schema/dictionary.rs` line 53 at r9](https://reviewable.io/reviews/datafuselabs/databend/16178#-O3ozf_6EagNogAJC4ZB:-O3ozf_6EagNogAJC4ZC:b-a4erlt) ([raw file](https://github.com/datafuselabs/databend/blob/25fec1be698c5a93067454d4f8bf434091398e96/src/meta/app/src/schema/dictionary.rs#L53)):*
> ```XML
>     // if used in CreateDictionaryReq,
>     // `updated_on` MUST set to None.
>     pub updated_on: Option<DateTime<Utc>>,
> ```

Use triple slash `///` doc comment for fields.



_Code quote:_
```XML
pub struct DictionaryMeta {
    // The source of the dictionary, which specifies where the dictionary data comes from, like `MySQL`.
    pub source: String,
    // Specify the configuration related to the data source in the form of key-value pairs.
    // For example, `host='localhost' user='root' password='1234'`
    pub options: BTreeMap<String, String>,
    // Schema refers to an external table that corresponds to the dictionary.
    // This is typically used to understand the layout and types of data within the dictionary.
    pub schema: Arc<TableSchema>,
    // A list of comments for each field in the dictionary.
    // For example, if we have `id, address` fields, then field_comments could be `[ 'student's number','home address']`
    pub field_comments: Vec<String>,
    // A list of primary column IDs.
    // For example, vec![1, 2] indicating the first and second columns are the primary keys.
    pub primary_column_ids: Vec<u32>,
    // A general comment string that can be used to provide additional notes or information about the dictionary.
    pub comment: String,
    // The timestamp indicating when the dictionary was created, in Coordinated Universal Time (UTC).
    pub created_on: DateTime<Utc>,
    // if used in CreateDictionaryReq,
    // `updated_on` MUST set to None.
    pub updated_on: Option<DateTime<Utc>>,
```
___
*[`src/meta/app/src/schema/dictionary.rs` line 181 at r9](https://reviewable.io/reviews/datafuselabs/databend/16178#-O3p-f335g0wdzK8ratJ:-O3p-f335g0wdzK8ratK:bjzj0f0) ([raw file](https://github.com/datafuselabs/databend/blob/25fec1be698c5a93067454d4f8bf434091398e96/src/meta/app/src/schema/dictionary.rs#L181)):*
> ```XML
> 
> #[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Eq)]
> pub struct DropDictionaryReply {}
> ```

It does not need `serde` IMHO.



_Code quote:_
```XML
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DropDictionaryReply {}
```
___
*[`src/meta/app/src/schema/dictionary.rs` line 189 at r9](https://reviewable.io/reviews/datafuselabs/databend/16178#-O3p-mLO0UTAdV8-ol4Q:-O3p-mLO0UTAdV8-ol4R:bjzj0f0) ([raw file](https://github.com/datafuselabs/databend/blob/25fec1be698c5a93067454d4f8bf434091398e96/src/meta/app/src/schema/dictionary.rs#L189)):*
> ```XML
> 
> #[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Eq)]
> pub struct GetDictionaryReply {
> ```

It does not need `serde` IMHO.



_Code quote:_
```XML
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct GetDictionaryReply {
```
___
*[`src/meta/app/src/schema/dictionary.rs` line 194 at r9](https://reviewable.io/reviews/datafuselabs/databend/16178#-O3p-Jvz3OxlDpD9RkZU:-O3p-Jvz3OxlDpD9RkZV:bsldpj5) ([raw file](https://github.com/datafuselabs/databend/blob/25fec1be698c5a93067454d4f8bf434091398e96/src/meta/app/src/schema/dictionary.rs#L194)):*
> ```XML
>     /// seq AKA version of this table snapshot.
>     /// Any change to a dictionary causes the seq to increment
>     pub seq: u64,
> ```

What `table snapshot` is that?



_Code quote:_
```XML
    /// seq AKA version of this table snapshot.
    /// Any change to a dictionary causes the seq to increment
    pub seq: u64,
```
___
*[`src/meta/app/src/schema/dictionary.rs` line 198 at r9](https://reviewable.io/reviews/datafuselabs/databend/16178#-O3p2PT143SkacWYZt10:-O3p2PT143SkacWYZt11:b-msiovt) ([raw file](https://github.com/datafuselabs/databend/blob/25fec1be698c5a93067454d4f8bf434091398e96/src/meta/app/src/schema/dictionary.rs#L198)):*
> ```XML
> 
> #[derive(Clone, Debug, Eq, PartialEq, Default)]
> pub struct DBIdDictionaryName {
> ```

This struct now represents a globally unique identifier for a `DictionaryMeta`. Rename it to `DictionaryIdent` to align with the codebase convention.
___
*[`src/meta/app/src/schema/dictionary.rs` line 201 at r9](https://reviewable.io/reviews/datafuselabs/databend/16178#-O3p0n0aBw_P9zf9z3Ti:-O3p0n0aBw_P9zf9z3Tj:b14pmkx) ([raw file](https://github.com/datafuselabs/databend/blob/25fec1be698c5a93067454d4f8bf434091398e96/src/meta/app/src/schema/dictionary.rs#L201)):*
> ```XML
>     pub db_id: u64,
>     pub dictionary_name: String,
> }
> ```

Define a meta-service key with `TIdent`, such as:
https://github.com/datafuselabs/databend/blob/3b57a6f043534271e41b10b050cae410dd78e9fc/src/meta/app/src/principal/tenant_user_ident.rs#L19

In your case the Dictionary Ident is an alias to `TIdent<Resource, DictionaryIdentity>`, where `DictionaryIdentity` includes the database id and dictionary name.

In the future every meta-service key must include a tenant in it, in order to support migration between meta-service clusters.



_Code quote:_
```XML
pub struct DBIdDictionaryName {
    pub db_id: u64,
    pub dictionary_name: String,
}
```


<!-- Sent from Reviewable.io -->

2024-08-09 02:56 UTC, drmingdrmer requested changes
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/16178)* status: 30 of 34 files reviewed, 17 unresolved discussions (waiting on @b41sh and @Winnie-Hong0927)

___
*[`src/meta/api/src/schema_api.rs` line 335 at r9](https://reviewable.io/reviews/datafuselabs/databend/16178#-O3p2tO53zutKhsBqk3R:-O3p2tO53zutKhsBqk3S:b-m2onfx) ([raw file](https://github.com/datafuselabs/databend/blob/25fec1be698c5a93067454d4f8bf434091398e96/src/meta/api/src/schema_api.rs#L335)):*
> ```XML
>         &self,
>         req: ListDictionaryReq,
>     ) -> Result<Vec<DictionaryMeta>, KVAppError>;
> ```

If the dictionary functions are just CRUD, consider re-using `CrudMgr` to implement these functions, such as ConnectionMgr does:

https://github.com/datafuselabs/databend/blob/98652d1a0fca41e8982b217362d9d1339300c86d/src/query/management/src/connection.rs#L18



_Code quote:_
```XML
    async fn create_dictionary(
        &self,
        req: CreateDictionaryReq,
    ) -> Result<CreateDictionaryReply, KVAppError>;

    async fn drop_dictionary(
        &self,
        req: DropDictionaryReq,
    ) -> Result<DropDictionaryReply, KVAppError>;

    async fn get_dictionary(
        &self,
        req: GetDictionaryReq,
    ) -> Result<Option<GetDictionaryReply>, KVAppError>;

    async fn list_dictionaries(
        &self,
        req: ListDictionaryReq,
    ) -> Result<Vec<DictionaryMeta>, KVAppError>;
```


<!-- Sent from Reviewable.io -->

2024-08-09 03:14 UTC, drmingdrmer commented
> > _[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/16178)_ status: 30 of 34 files reviewed, 17 unresolved discussions (waiting on @b41sh and @Winnie-Hong0927)
> 
> _[`src/meta/api/src/schema_api.rs` line 335 at r9](https://reviewable.io/reviews/datafuselabs/databend/16178#-O3p2tO53zutKhsBqk3R:-O3p2tO53zutKhsBqk3S:b-m2onfx) ([raw file](https://github.com/datafuselabs/databend/blob/25fec1be698c5a93067454d4f8bf434091398e96/src/meta/api/src/schema_api.rs#L335)):_
> 
> > ```
> >         &self,
> >         req: ListDictionaryReq,
> >     ) -> Result<Vec<DictionaryMeta>, KVAppError>;
> > ```
> 
> If the dictionary functions are just CRUD, consider re-using `CrudMgr` to implement these functions, such as ConnectionMgr does:
> 
> https://github.com/datafuselabs/databend/blob/98652d1a0fca41e8982b217362d9d1339300c86d/src/query/management/src/connection.rs#L18
> 
> _Code quote:_
> 
> ```
>     async fn create_dictionary(
>         &self,
>         req: CreateDictionaryReq,
>     ) -> Result<CreateDictionaryReply, KVAppError>;
> 
>     async fn drop_dictionary(
>         &self,
>         req: DropDictionaryReq,
>     ) -> Result<DropDictionaryReply, KVAppError>;
> 
>     async fn get_dictionary(
>         &self,
>         req: GetDictionaryReq,
>     ) -> Result<Option<GetDictionaryReply>, KVAppError>;
> 
>     async fn list_dictionaries(
>         &self,
>         req: ListDictionaryReq,
>     ) -> Result<Vec<DictionaryMeta>, KVAppError>;
> ```

CrudMgr does not support non-string identifier. Please ignore this comment.

2024-08-10 02:36 UTC, drmingdrmer requested changes
> Reviewed 8 of 8 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/16178)* status: all files reviewed, 10 unresolved discussions (waiting on @b41sh and @Winnie-Hong0927)

___
*[`src/meta/api/src/schema_api_impl.rs` line 4314 at r10](https://reviewable.io/reviews/datafuselabs/databend/16178#-O3u25Md0_pVqku7u0dh:-O3u25Md0_pVqku7u0di:blrt9vv) ([raw file](https://github.com/datafuselabs/databend/blob/9179adceea2f8b16b422b132fe25e55dd7740221/src/meta/api/src/schema_api_impl.rs#L4314)):*
> ```XML
>                     }
>                 }
>             }
> ```

I'd recommend to split this part of logic into two API:
- one API for `CreateOption::Create` and `CreateOption::CreateIfNotExists`, these two case does not need a transaction but just add a condition to assert the seq of dictionary-id to be zero. The only difference is the return value handling, which actually should be the duty of the caller but not at schema API level.
- the other API for `CreateOption::CreateOrReplace`, which may override existing value thus it needs a CAS loop transaction.

The two API could be `create_dictionary` and `update_dictionary`, which are better reflecting their purposes.



_Code quote:_
```XML
            if dictionary_id_seq > 0 {
                match req.create_option {
                    CreateOption::Create => {
                        return Err(KVAppError::AppError(AppError::DictionaryAlreadyExists(
                            DictionaryAlreadyExists::new(
                                tenant_dictionary.dict_name(),
                                format!(
                                    "create dictionary with tenant: {}",
                                    tenant_dictionary.tenant_name()
                                ),
                            ),
                        )));
                    }
                    CreateOption::CreateIfNotExists => {
                        return Ok(CreateDictionaryReply { dictionary_id });
                    }
                    CreateOption::CreateOrReplace => {
                    // delete old dictionary meta
                    // (dictionary_id) -> dictionary_meta
                        let old_id_key = DictionaryId { dictionary_id };
                        condition.push(txn_cond_seq(&old_id_key, Eq, dictionary_meta_seq));
                        if_then.push(txn_op_del(&old_id_key));
                    }
                }
            }
```
___
*[`src/meta/api/src/schema_api_impl.rs` line 4388 at r10](https://reviewable.io/reviews/datafuselabs/databend/16178#-O3u3RNw7g18_zKcNMAQ:-O3u3RNw7g18_zKcNMAR:bxvddpe) ([raw file](https://github.com/datafuselabs/databend/blob/9179adceea2f8b16b422b132fe25e55dd7740221/src/meta/api/src/schema_api_impl.rs#L4388)):*
> ```XML
>                     )));
>                 }
>             }
> ```

schema API does not use `if_exists` at all, which is totally return value handling and should be the caller's duty.



_Code quote:_
```XML
            let drop_if_exists = req.if_exists;

            if dictionary_id_seq == 0 {
                if drop_if_exists {
                    return Ok(DropDictionaryReply {});
                } else {
                    return Err(KVAppError::AppError(AppError::UnknownDictionary(
                        UnknownDictionary::new(dictionary_ident.dict_name().clone(), "drop_dictionary"),
                    )));
                }
            }
```
___
*[`src/meta/api/src/schema_api_impl.rs` line 4486 at r10](https://reviewable.io/reviews/datafuselabs/databend/16178#-O3u5Jp14XSYgQl0bM_U:-O3u5Jp14XSYgQl0bM_V:b-lxhtx8) ([raw file](https://github.com/datafuselabs/databend/blob/9179adceea2f8b16b422b132fe25e55dd7740221/src/meta/api/src/schema_api_impl.rs#L4486)):*
> ```XML
>                 debug!(k = &dict_meta_keys[i]; "dict_meta not found");
>             }
>         }
> ```

This `mget` could be very large, split it into chunks, reference to:
https://github.com/datafuselabs/databend/blob/cb33a8ef54fc60ea2ae30d8b8b87c0fc2688428b/src/meta/api/src/schema_api_impl.rs#L2321



_Code quote:_
```XML
        let seq_dict_metas = self.mget_kv(&dict_meta_keys).await?;
        let mut dict_metas = Vec::with_capacity(seq_dict_metas.len());
        for (i, (key, seq_meta_opt)) in dict_keys.into_iter().zip(seq_dict_metas.into_iter()).enumerate() {
            if let Some(seq_meta) = seq_meta_opt {
                let dict_meta: DictionaryMeta = deserialize_struct(&seq_meta.data)?;
                dict_metas.push((key.dict_name().clone(), dict_meta));
            } else {
                debug!(k = &dict_meta_keys[i]; "dict_meta not found");
            }
        }
```
___
*[`src/meta/app/src/principal/dictionary_identity.rs` line 20 at r10](https://reviewable.io/reviews/datafuselabs/databend/16178#-O3u6-TB5ETdfv7gU-21:-O3u6-TB5ETdfv7gU-22:b-vf3wff) ([raw file](https://github.com/datafuselabs/databend/blob/9179adceea2f8b16b422b132fe25e55dd7740221/src/meta/app/src/principal/dictionary_identity.rs#L20)):*
> ```XML
>     pub db_id: u64,
>     pub dict_name: String,
> }
> ```

Does it need serde?



_Code quote:_
```XML
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, Eq, PartialEq, Hash, Default)]
pub struct DictionaryIdentity {
    pub db_id: u64,
    pub dict_name: String,
}
```
___
*[`src/meta/app/src/principal/tenant_dictionary_ident.rs` line 35 at r10](https://reviewable.io/reviews/datafuselabs/databend/16178#-O3u6P0CB6SIYMCPGCOo:-O3u6P0CB6SIYMCPGCOp:b-54cyv4) ([raw file](https://github.com/datafuselabs/databend/blob/9179adceea2f8b16b422b132fe25e55dd7740221/src/meta/app/src/principal/tenant_dictionary_ident.rs#L35)):*
> ```XML
>     pub fn new_dict_db(tenant: impl ToTenant, dict_name: impl ToString, db_id: u64) -> Self {
>         Self::new(tenant, DictionaryIdentity::new(db_id, dict_name))
>     }
> ```

`db_id` is the container object, put `db_id` before `dict_name`.



_Code quote:_
```XML
    pub fn new_dict_db(tenant: impl ToTenant, dict_name: impl ToString, db_id: u64) -> Self {
        Self::new(tenant, DictionaryIdentity::new(db_id, dict_name))
    }
```
___
*[`src/meta/app/src/schema/dictionary.rs` line 134 at r10](https://reviewable.io/reviews/datafuselabs/databend/16178#-O3u7K39EunIyI8WmDlN:-O3u7K39EunIyI8WmDlO:b-qsw79e) ([raw file](https://github.com/datafuselabs/databend/blob/9179adceea2f8b16b422b132fe25e55dd7740221/src/meta/app/src/schema/dictionary.rs#L134)):*
> ```XML
> pub struct GetDictionaryReq {
>     pub dictionary_ident: TenantDictionaryIdent,
> }
> ```

Replace `GetDictionaryReq` with `TenantDictionaryIdent`, since it is just a wrapper providing no additional functions. Using `TenantDictionaryIdent` could be more explicit.



_Code quote:_
```XML
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct GetDictionaryReq {
    pub dictionary_ident: TenantDictionaryIdent,
}
```


<!-- Sent from Reviewable.io -->

2024-08-11 04:10 UTC, drmingdrmer requested changes
> Reviewed 4 of 5 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/16178)* status: 36 of 37 files reviewed, 15 unresolved discussions (waiting on @b41sh and @Winnie-Hong0927)

___
*[`src/meta/api/src/schema_api_impl.rs` line 4285 at r11](https://reviewable.io/reviews/datafuselabs/databend/16178#-O3zbKdvCcEUDU1Glpx2:-O3zbKdvCcEUDU1Glpx3:b-5otjyc) ([raw file](https://github.com/datafuselabs/databend/blob/9b13eccebe28f26b9949cbd825159b42ab0a0431/src/meta/api/src/schema_api_impl.rs#L4285)):*
> ```XML
>                 dictionary_name: dictionary_ident.dictionary_name.clone(),
>             };
>             let res = get_dictionary_or_err(self, &dict_ident).await?;
> ```

use `TenantDictionaryIdent` to access meta-service.



_Code quote:_
```XML
            let dict_ident = DictionaryIdent {
                db_id: dictionary_ident.db_id,
                dictionary_name: dictionary_ident.dictionary_name.clone(),
            };
            let res = get_dictionary_or_err(self, &dict_ident).await?;
```
___
*[`src/meta/api/src/schema_api_impl.rs` line 4385 at r11](https://reviewable.io/reviews/datafuselabs/databend/16178#-O3zbRN04JuOg2_D3H82:-O3zbRN04JuOg2_D3H83:b-rziabo) ([raw file](https://github.com/datafuselabs/databend/blob/9b13eccebe28f26b9949cbd825159b42ab0a0431/src/meta/api/src/schema_api_impl.rs#L4385)):*
> ```XML
> 
>             let res: (u64, u64, u64, Option<DictionaryMeta>) =
>                 get_dictionary_or_err(self, &dictionary_ident).await?;
> ```

use `TenantDictionaryIdent`.



_Code quote:_
```XML
        let dictionary_ident = DictionaryIdent {
            db_id: req.dictionary_ident.db_id(),
            dictionary_name: req.dictionary_ident.dict_name().clone(),
        };
        let mut trials = txn_backoff(None, func_name!());

        loop {
            trials.next().unwrap()?.await;

            let mut condition = vec![];
            let mut if_then = vec![];

            let res: (u64, u64, u64, Option<DictionaryMeta>) =
                get_dictionary_or_err(self, &dictionary_ident).await?;
```
___
*[`src/meta/api/src/schema_api_impl.rs` line 4447 at r11](https://reviewable.io/reviews/datafuselabs/databend/16178#-O3zbTpA-0lnHHBLPACb:-O3zbTpA-0lnHHBLPACc:b-rziabo) ([raw file](https://github.com/datafuselabs/databend/blob/9b13eccebe28f26b9949cbd825159b42ab0a0431/src/meta/api/src/schema_api_impl.rs#L4447)):*
> ```XML
>         };
> 
>         let res = get_dictionary_or_err(self, &dictionary_ident).await?;
> ```

use `TenantDictionaryIdent`.



_Code quote:_
```XML
        let dictionary_ident = DictionaryIdent {
            db_id: req.dictionary_ident.db_id(),
            dictionary_name: req.dictionary_ident.dict_name().clone(),
        };

        let res = get_dictionary_or_err(self, &dictionary_ident).await?;
```
___
*[`src/meta/api/src/schema_api_impl.rs` line 4484 at r11](https://reviewable.io/reviews/datafuselabs/databend/16178#-O3zbVUe9Q4oICgI9Mpk:-O3zbVUe9Q4oICgI9Mpl:b-rziabo) ([raw file](https://github.com/datafuselabs/databend/blob/9b13eccebe28f26b9949cbd825159b42ab0a0431/src/meta/api/src/schema_api_impl.rs#L4484)):*
> ```XML
>         };
> 
>         let (dict_keys, dict_id_list) = list_u64_value(self, &dictionary_ident).await?;
> ```

use `TenantDictionaryIdent`.



_Code quote:_
```XML
        let dictionary_ident = DictionaryIdent {
            db_id: req.db_id,
            dictionary_name: "".to_string(),
        };

        let (dict_keys, dict_id_list) = list_u64_value(self, &dictionary_ident).await?;
```
___
*[`src/meta/app/src/schema/dictionary.rs` line 106 at r11](https://reviewable.io/reviews/datafuselabs/databend/16178#-O3zbgSZ14brDNmGyDmT:-O3zbgSZ14brDNmGyDmU:b2za1f2) ([raw file](https://github.com/datafuselabs/databend/blob/9b13eccebe28f26b9949cbd825159b42ab0a0431/src/meta/app/src/schema/dictionary.rs#L106)):*
> ```XML
>         tenant: impl ToTenant,
>     ) -> DropDictionaryReq {
>         let dictionary_ident = TenantDictionaryIdent::new_dict_db(tenant, dict_name, db_id);
> ```

Create DropDictionaryReq with`TenantDictionaryIdent`, or there are too many arguments



_Code quote:_
```XML
impl DropDictionaryReq {
    pub fn new(
        if_exists: bool,
        db_id: u64,
        dict_name: String,
        tenant: impl ToTenant,
    ) -> DropDictionaryReq {
        let dictionary_ident = TenantDictionaryIdent::new_dict_db(tenant, dict_name, db_id);
```


<!-- Sent from Reviewable.io -->

2024-08-12 02:15 UTC, sundy-li commented
let's make it ready to review util all tests are passed.

2024-08-12 04:23 UTC, drmingdrmer reviewed
> Reviewed 10 of 10 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/16178)* status: all files reviewed, 13 unresolved discussions (waiting on @b41sh and @Winnie-Hong0927)

___
*[`src/meta/api/src/schema_api_impl.rs` line 4373 at r12](https://reviewable.io/reviews/datafuselabs/databend/16178#-O43m68cDIQwwQnHuOjN:-O43m68dBw0SDLHz9fT3:b-smrp4e) ([raw file](https://github.com/datafuselabs/databend/blob/2f541407fcb0f34a730b5034e9b105bce8948ac2/src/meta/api/src/schema_api_impl.rs#L4373)):*
> ```XML
>             db_id: dict_ident.db_id(),
>             dictionary_name: dict_ident.dict_name().clone(),
>         };
> ```

Use `TenantDictionaryIdent`



_Code quote:_
```XML
        let dictionary_ident = DictionaryIdent {
            db_id: dict_ident.db_id(),
            dictionary_name: dict_ident.dict_name().clone(),
        };
```
___
*[`src/meta/app/src/principal/dictionary_identity.rs` line 62 at r12](https://reviewable.io/reviews/datafuselabs/databend/16178#-O43nSXaEE8BJKayrKC9:-O43nSXaEE8BJKayrKCA:b2vjx53) ([raw file](https://github.com/datafuselabs/databend/blob/2f541407fcb0f34a730b5034e9b105bce8948ac2/src/meta/app/src/principal/dictionary_identity.rs#L62)):*
> ```XML
>             Some(DatabaseId::new(self.db_id).to_string_key())
>         }
>     }
> ```

`DictionaryIdentity` should not be implemented as `kvapi::Key`. it has no `Tenant` and should not be used directly.



_Code quote:_
```XML
    impl kvapi::Key for DictionaryIdentity {
        const PREFIX: &'static str = "__fd_dictionary";

        type ValueType = DictionaryId;

        fn parent(&self) -> Option<String> {
            Some(DatabaseId::new(self.db_id).to_string_key())
        }
    }
```
___
*[`src/meta/app/src/principal/tenant_dictionary_ident.rs` line 31 at r12](https://reviewable.io/reviews/datafuselabs/databend/16178#-O43ng8l1OGpJ0TNkr9V:-O43ng8l1OGpJ0TNkr9W:b-b46ih0) ([raw file](https://github.com/datafuselabs/databend/blob/2f541407fcb0f34a730b5034e9b105bce8948ac2/src/meta/app/src/principal/tenant_dictionary_ident.rs#L31)):*
> ```XML
>     }
> 
>     pub fn new_dict_db(tenant: impl ToTenant, db_id: u64, dict_name: impl ToString) -> Self {
> ```

The name `new_dict_db` should be update to reflect the arguments passed in.
___
*[`src/meta/app/src/schema/dictionary.rs` line 94 at r12](https://reviewable.io/reviews/datafuselabs/databend/16178#-O43o32J9qo3iWj742A8:-O43o32J9qo3iWj742A9:b-pw0z95) ([raw file](https://github.com/datafuselabs/databend/blob/2f541407fcb0f34a730b5034e9b105bce8948ac2/src/meta/app/src/schema/dictionary.rs#L94)):*
> ```XML
> 
> #[derive(Clone, Debug, PartialEq, Eq)]
> pub struct DropDictionaryReply {}
> ```

Is this struct used anymore?
___
*[`src/meta/proto-conv/tests/it/v105_dictionary_meta.rs` line 81 at r12](https://reviewable.io/reviews/datafuselabs/databend/16178#-O43oigZ6vo4vWxttTFH:-O43oigZ6vo4vWxttTFI:b-qanlj5) ([raw file](https://github.com/datafuselabs/databend/blob/2f541407fcb0f34a730b5034e9b105bce8948ac2/src/meta/proto-conv/tests/it/v105_dictionary_meta.rs#L81)):*
> ```XML
> 
>     common::test_pb_from_to(func_name!(), want())?;
>     // common::test_load_old(func_name!(), bytes.as_slice(), 105, want())?;
> ```

Why it is commented?


<!-- Sent from Reviewable.io -->

2024-08-12 08:11 UTC, drmingdrmer reviewed
> Reviewed 2 of 2 files at r13, 3 of 4 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/16178)* status: 36 of 37 files reviewed, 15 unresolved discussions (waiting on @b41sh and @Winnie-Hong0927)

___
*[`src/meta/app/src/schema/dictionary.rs` line 161 at r14](https://reviewable.io/reviews/datafuselabs/databend/16178#-O44crdB8d28ubUyMo4K:-O44crdB8d28ubUyMo4L:b-1e6da1) ([raw file](https://github.com/datafuselabs/databend/blob/54542123553c0d4182c7c38251c7db208c8b32b5/src/meta/app/src/schema/dictionary.rs#L161)):*
> ```XML
>     pub dict_name: String,
>     pub dict_meta: DictionaryMeta,
> }
> ```

It does not need serde.

Update needs exactly one of dictionary-id or dictionary-name.



_Code quote:_
```XML
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct UpdateDictionaryReq {
    pub dict_id: u64,
    pub dict_name: String,
    pub dict_meta: DictionaryMeta,
}
```
___
*[`src/meta/app/src/schema/dictionary.rs` line 164 at r14](https://reviewable.io/reviews/datafuselabs/databend/16178#-O44d2eIDIKLZZuCCJca:-O44d2eIDIKLZZuCCJcb:b73px2t) ([raw file](https://github.com/datafuselabs/databend/blob/54542123553c0d4182c7c38251c7db208c8b32b5/src/meta/app/src/schema/dictionary.rs#L164)):*
> ```XML
> 
> #[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq, Eq)]
> pub struct UpdateDictionaryReply {}
> ```

remove this struct if it is empty. use `()` instead


<!-- Sent from Reviewable.io -->

2024-08-12 13:58 UTC, drmingdrmer reviewed
> Reviewed 7 of 9 files at r15, 3 of 3 files at r16, 4 of 4 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/16178)* status: all files reviewed, 2 unresolved discussions (waiting on @b41sh and @Winnie-Hong0927)



<!-- Sent from Reviewable.io -->

2024-08-12 17:28 UTC, drmingdrmer approved these changes
Thank you, good job!

> Reviewed 3 of 3 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/16178#-:-O46cS_r58PQzGRIhAnz:b95u1tb)* status: all files reviewed, 1 unresolved discussion (waiting on @b41sh and @Winnie-Hong0927)



<!-- Sent from Reviewable.io -->

2024-08-13 01:52 UTC, b41sh approved these changes

2024-08-13 04:47 UTC, drmingdrmer approved these changes
> Reviewed 1 of 1 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/16178)* status: all files reviewed, 1 unresolved discussion (waiting on @Winnie-Hong0927)



<!-- Sent from Reviewable.io -->

2024-08-13 04:48 UTC, drmingdrmer approved these changes
> *[Reviewable](https://reviewable.io/reviews/datafuselabs/databend/16178)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Winnie-Hong0927)



<!-- Sent from Reviewable.io -->

2024-08-13 06:12 UTC, merged