ISSUE-3557: Add rename table command
datafuselabs/databend pull request #4425
Opened 2022-03-13 08:26 UTC by kevinw66

I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/

## Summary

Add rename table command

## Changelog

- New Feature

## Related Issues

Fixes #3557

## Test Plan

Unit Tests

Stateless Tests

2022-03-13 12:48 UTC, BohuTANG commented
@mergify update

2022-03-13 13:12 UTC, Junnplus requested changes
Thanks!

We may need some unit tests for interpreter and parser.

2022-03-14 06:52 UTC, kevinw66 commented
> Thanks!
> 
> We may need some unit tests for interpreter and parser.

@Junnplus Done

2022-03-15 01:40 UTC, Junnplus commented on common/planners/src/plan_table_rename.rs
> +    pub maps: Vec<RenameTableMap>,
`entities` could be better.

2022-03-15 02:45 UTC, kevinw66 commented
> Hi @kevinw66 ,
> 
> Thanks for the cool feature. Is it possible to add a stateless test for the `rename table`? For example, the `truncate table` stateless test is: https://github.com/datafuselabs/databend/blob/85878247b295863000134ab569205ae7a9247b08/tests/suites/0_stateless/05_ddl/05_0003_ddl_truncate_table.sql

What's the name rule ? I saw two 05_0000 sql file and none 05_0002 sql file

2022-03-15 02:49 UTC, BohuTANG commented
> > Hi @kevinw66 ,
> > Thanks for the cool feature. Is it possible to add a stateless test for the `rename table`? For example, the `truncate table` stateless test is: https://github.com/datafuselabs/databend/blob/85878247b295863000134ab569205ae7a9247b08/tests/suites/0_stateless/05_ddl/05_0003_ddl_truncate_table.sql
> 
> What's the name rule ? I saw two 05_0000 sql file and none 05_0002 sql file

`05_0003` is the ddl/table catagory, we can name it to:
`05_0003_ddl_rename_table.sql`

2022-03-15 04:27 UTC, BohuTANG commented
```
--- /home/runner/work/databend/databend/tests/suites/0_stateless/05_ddl/05_0003_ddl_rename_table.result	2022-03-15 03:56:35.945918604 +0000
+++ /home/runner/work/databend/databend/tests/suites/0_stateless/05_ddl/05_0003_ddl_rename_table.stdout	2022-03-15 03:58:22.258501441 +0000
@@ -1,3 +1,7 @@
+ERROR 1105 (HY000) at line 7: Code: 2302, displayText = table exists: t1.
+ERROR 1105 (HY000) at line 8: Code: 1054, displayText = Expected server error code: 1025 but got: Ok..
+1	NULL
+2	3
+1
 1
 1
-1
\ No newline at end of file
```

2022-03-15 05:26 UTC, kevinw66 commented
> ```
> --- /home/runner/work/databend/databend/tests/suites/0_stateless/05_ddl/05_0003_ddl_rename_table.result	2022-03-15 03:56:35.945918604 +0000
> +++ /home/runner/work/databend/databend/tests/suites/0_stateless/05_ddl/05_0003_ddl_rename_table.stdout	2022-03-15 03:58:22.258501441 +0000
> @@ -1,3 +1,7 @@
> +ERROR 1105 (HY000) at line 7: Code: 2302, displayText = table exists: t1.
> +ERROR 1105 (HY000) at line 8: Code: 1054, displayText = Expected server error code: 1025 but got: Ok..
> +1	NULL
> +2	3
> +1
>  1
>  1
> -1
> \ No newline at end of file
> ```

Is this because `02_0045_function_in.sql` create table `t1` but forgot to drop it?

2022-03-15 05:30 UTC, BohuTANG commented
> > ```
> > --- /home/runner/work/databend/databend/tests/suites/0_stateless/05_ddl/05_0003_ddl_rename_table.result	2022-03-15 03:56:35.945918604 +0000
> > +++ /home/runner/work/databend/databend/tests/suites/0_stateless/05_ddl/05_0003_ddl_rename_table.stdout	2022-03-15 03:58:22.258501441 +0000
> > @@ -1,3 +1,7 @@
> > +ERROR 1105 (HY000) at line 7: Code: 2302, displayText = table exists: t1.
> > +ERROR 1105 (HY000) at line 8: Code: 1054, displayText = Expected server error code: 1025 but got: Ok..
> > +1	NULL
> > +2	3
> > +1
> >  1
> >  1
> > -1
> > \ No newline at end of file
> > ```
> 
> Is this because `02_0045_function_in.sql` create table `t1` but forgot to drop it?

Use another table name here?

2022-03-15 07:29 UTC, BohuTANG commented
```
05_0003_ddl_rename_table:                                               [ FAIL ] - result differs with:
--- /Users/runner/work/databend/databend/tests/suites/0_stateless/05_ddl/05_0003_ddl_rename_table.result	2022-03-15 06:07:26.000000000 +0000
+++ /Users/runner/work/databend/databend/tests/suites/0_stateless/05_ddl/05_0003_ddl_rename_table.stdout	2022-03-15 06:10:03.000000000 +0000
@@ -1,3 +1,3 @@
 1
 1
-1
\ No newline at end of file
+1

```

It seems we should append a newline to the end of the result file.

2022-03-15 10:23 UTC, Junnplus approved these changes
Thanks!

LGTM on green.

2022-03-15 11:09 UTC, merged